import time
import csv
from selenium import webdriver
from bs4 import BeautifulSoup

jobs_list=["Software Engineering Jobs",
"Java Jobs",
"Javascript Jobs",
"Technical Support Jobs",
"Python Jobs",
"Sql Jobs",
"Computer Operator Jobs",
"HTML Jobs",
"CSS Jobs",
"AWS Jobs",
"C# Jobs",
"Networking Jobs",
"Receptionist Jobs",
"Angular Jobs",
"Agile Jobs",
"Linux Jobs",
"Html5 Jobs",
"Cloud Jobs",
"Git Jobs",
".NET Jobs",
"Azure Jobs",
"Technical Support Executive Jobs",
"Kpo Jobs",
"Testing Jobs",
"Spring Jobs",
"Software Engineer Jobs",
"Devops Jobs",
"C++ Jobs",
"Mvc Jobs",
"Oracle Jobs",
"Hibernate Jobs",
"Php Jobs",
"Core Java Jobs",
"jQuery Jobs",
"Spring Boot Jobs",
"Xml Jobs",
"Web Services Jobs",
"Technical Recruiter Jobs",
"Json Jobs",
"Tech Support Jobs",
"Tech Support Jobs",
"SQL Server Jobs",
"MySQL Jobs",
"Sales Manager Jobs",
"Microservices Jobs",
"Computer operator Jobs",
"Css3 Jobs",
"Windows Jobs",
"Docker Jobs",
"J2EE Jobs",
"Desktop Support Jobs",
"C Jobs",
"Jenkins Jobs",
"Technical Support Engineer Jobs",
"react.js  Jobs",
"SAP Jobs",
"Dns Jobs",
"Coding Jobs",
"Kubernetes Jobs",
"Selenium Jobs",
"Automation Jobs",
"Software Developer Jobs",
"MongoDB Jobs",
"Web Technologies Jobs",
"Information Technology Jobs",
"Spark Jobs",
"Database Jobs",
"JIRA Jobs",
"Software Development Jobs",
"technical support Jobs",
"Tally Jobs",
"Bootstrap Jobs",
"Front End Jobs",
"Soap Jobs",
"Unix Jobs",
"Machine Learning Jobs",
"Program Jobs",
"Angularjs Jobs",
"Sales Executive Jobs",
"SEO Jobs",
"DHCP Jobs",
"Scrum Jobs",
"Hadoop Jobs",
"REST Jobs",
"Debugging Jobs",
"JQuery Jobs",
"Performance Tuning Jobs",
"Angular Js Jobs",
"Team Leader Jobs",
"Project Manager Jobs",
"Quality Assurance Jobs",
"Excel Jobs",
"Nosql Jobs",
"Android Jobs",
"Application Development Jobs",
"Node.js Jobs",
"React Jobs",
"Sdlc Jobs",
"Erp Jobs",
"Kafka Jobs",
"Automation Testing Jobs",
"Search Engine Optimization Jobs",
"Maven Jobs",
"Big Data Jobs",
"Configuration Jobs",
"Perl Jobs",
"Production Engineer Jobs",
"Qa Jobs",
"Vmware Jobs",
"Ms Office Jobs",
"Nodejs Jobs",
"Unit Testing Jobs",
"Scala Jobs",
"Etl Jobs",
"Manual Testing Jobs",
"Operations Executive Jobs",
"Ios Jobs",
"Api Jobs",
"ASP.NET Jobs",
"Web Api Jobs",
"Design Patterns Jobs",
"It Helpdesk Jobs",
"Reactjs Jobs",
"Sql Database Jobs",
"AJAX Jobs",
"Rest Api Jobs",
"Exchange Server Jobs",
"RDBMS Jobs",
"Maintenance Engineer Jobs",
"technology architecture  Jobs",
"Php developer Jobs",
"Technical support Jobs",
"Oops Jobs",
"Programming Jobs",
"Ansible Jobs",
"Jsp Jobs",
"Power Bi Jobs",
"Coder Jobs",
"Data Modeling Jobs",
"React Js Jobs",
"SSIS Jobs",
"Redux Jobs",
"python Jobs",
"Algorithms Jobs",
"Mysql Jobs",
"Quality Jobs",
"Data Warehousing Jobs",
"Java Script Jobs",
"Typescript Jobs",
"Ajax Jobs",
"Hive Jobs",
"Sap Abap Jobs",
"Technical Lead Jobs",
"Ui Development Jobs",
"Ruby Jobs",
"Data Management Jobs",
"Windows Server Jobs",
"Production Supervisor Jobs",
"Test Cases Jobs",
"Gcp Jobs",
"Scripting Jobs",
"Plsql Jobs",
"Microsoft Jobs",
"Adobe Photoshop Jobs",
"Server Support Jobs",
"Software Testing Jobs",
"Programmer Jobs",
"Lan Jobs",
"Laptop Support Jobs",
"Senior Manager Jobs",
"MS SQL Jobs",
"Apache Jobs",
"Laravel Jobs",
"Node JS Jobs",
"React Native Jobs",
"Web Designer Jobs",
"Wcf Jobs",
"J2Ee Jobs",
"Dot Net Jobs",
"Powershell Jobs",
"Research Jobs",
"Solution Architect Jobs",
"Sql Queries Jobs",
"Swift Jobs",
"Dotnet Jobs",
"Recruitment Executive Jobs",
"ASP.Net Jobs",
"Tableau Jobs",
"Functional Testing Jobs",
"DB2 Jobs",
"SFDC Jobs",
"System Administrator Jobs",
"Technical Architect Jobs",
"UNIX Jobs",
"email process  Jobs",
"Itil Jobs",
"Mca Jobs",
"Devops Engineer Jobs",
"SAS Jobs",
"Data structures Jobs",
"Network Engineer Jobs",
"PostgreSQL Jobs",
"Agile Methodology Jobs",
"Http Jobs",
"IT Recruitment Jobs",
"Application Support Jobs",
"Springboot Jobs",
"Ms Excel Jobs",
"Sales Development Manager Jobs",
"Virtualization Jobs",
"tech support Jobs",
"Asp.Net Jobs",
"Soa Jobs",
"Jms Jobs",
"Jquery Jobs",
"Multithreading Jobs",
"Open Source Jobs",
"Rest Jobs",
"Tomcat Jobs",
"System Administration Jobs",
"Github Jobs",
"Product Manager Jobs",
"Informatica Jobs",
"Program Manager Jobs",
"Splunk Jobs",
"Agile Development Jobs",
"Data Analytics Jobs",
"Network Administrator Jobs",
"Struts Jobs",
"Wan Jobs",
"Apex Jobs",
"Entity Framework Jobs",
"PL/SQL Jobs",
"Sap Fico Jobs",
"It Sales Jobs",
"Servicenow Jobs",
"Software Design Jobs",
"Team Manager Jobs",
"Wordpress Jobs",
"Performance Testing Jobs",
"JDBC Jobs",
"Shell scripting Jobs",
"Ssrs Jobs",
"Weblogic Jobs",
"Cobol Jobs",
"Test Engineer Jobs",
"Micro Services Jobs",
"Salesforce.com Jobs",
"Senior Software Engineer Jobs",
"Cloud Computing Jobs",
"Incident Management Jobs",
"Technical Support Associate Jobs",
"Asp.net Mvc Jobs",
"Data Engineer Jobs",
"Ibm Jobs",
"Software programmer Jobs",
"Cassandra Jobs",
"Django Jobs",
"Workflow Jobs",
"3d Max Jobs",
"Adobe Illustrator Jobs",
"Information Security Jobs",
"Senior Accountant Jobs",
"Android SDK Jobs",
"Ccna Jobs",
"Svn Jobs",
"Cyber Security Jobs",
"Firewall Jobs",
"RESTful Jobs",
"Technical Helpdesk Jobs",
"Google Analytics Jobs",
"It Service Desk Jobs",
"Quality Analyst Jobs",
"Team Leading Jobs",
"Terraform Jobs",
"Data Structures Jobs",
"Operating Systems Jobs",
"Paas Jobs",
"data structures Jobs",
"Animation Jobs",
"Saas Jobs",
"Unix Shell Scripting Jobs",
"C#.net Jobs",
"Technical Support Representative Jobs",
"Ms Sql Server Jobs",
"Sales executive Jobs",
"Software developer Jobs",
"Tdd Jobs",
"Web Development Jobs",
"Bash Jobs",
"UI Jobs",
"Data Migration Jobs",
"Lightning Jobs",
"Os Installation Jobs",
"Qa Engineer Jobs",
"JCL Jobs",
"Remote Support Jobs",
"IT Support Jobs",
"Jpa Jobs",
"Magento Jobs",
"Ux Jobs",
"Web development Jobs",
"agile Jobs",
"Scrum Master Jobs",
"Spring Framework Jobs",
"Wpf Jobs",
"Laptop Jobs",
"Webservices Jobs",
"Database Design Jobs",
"Network Jobs",
"Oracle Sql Jobs",
"Routing Jobs",
"web chat  Jobs",
"Cisco Jobs",
"Oracle database Jobs",
"Service Engineer Jobs",
"Api Testing Jobs",
"Drupal Jobs",
"Production Executive Jobs",
"Shell Scripting Jobs",
"Software Development Engineer Jobs",
"Ar Jobs",
"Jira Jobs",
"Kotlin Jobs",
"Servlets Jobs",
"System Architecture Jobs",
"sales executive Jobs",
"Hardware Networking Jobs",
"Process Associate Jobs",
"Python Developer Jobs",
"Rpa Jobs",
"automation Jobs",
"Desktop Engineer Jobs",
"Jboss Jobs",
"Lecturer Jobs",
"Project Engineer Jobs",
"Visualforce Jobs",
"linux Jobs",
"Microsoft Azure Jobs",
"Node.Js Jobs",
"Oracle Dba Jobs",
"Shell Jobs",
"Asm Jobs",
"Codeigniter Jobs",
"Html 5 Jobs",
"Jmeter Jobs",
"Sap Basis Jobs",
"Data Quality Jobs",
"Object Oriented Programming Jobs",
"Troubleshoot Jobs",
"Continuous Integration Jobs",
"Itsm Jobs",
"Puppet Jobs",
"Test Scripts Jobs",
"Vba Jobs",
"Dba Jobs",
"Hana Jobs",
"Quality Engineer Jobs",
"S3 Jobs",
"Software Tester Jobs",
"knowledge process outsourcing  Jobs",
"Automation testing Jobs",
"Middleware Jobs",
"Project Delivery Jobs",
"Storage Jobs",
"Artificial Intelligence Jobs",
"Electrician Jobs",
"PHP programmer Jobs",
"Sales Engineer Jobs",
"Switches Jobs",
"Technical Sales Jobs",
"html Jobs",
"tally Jobs",
"Bitbucket Jobs",
"Production Officer Jobs",
"Tcp/ip Jobs",
"Web Application Jobs",
"cloud Jobs",
"Data Visualization Jobs",
"Junit Jobs",
"Office 365 Jobs",
"System Admin Jobs",
"Visual Studio Jobs",
"It Infrastructure Jobs",
"Ldap Jobs",
"Postgresql Jobs",
"Appium Jobs",
"Php Mysql Jobs",
"Routers Jobs",
"Solution Architecture Jobs",
"Windows Troubleshooting Jobs",
"Abap Jobs",
"Cms Jobs",
"Cucumber Jobs",
"Golang Jobs",
"Oracle Cloud Jobs",
"Postgres Jobs",
"SCCM Jobs",
"Sales Head Jobs",
"Sap Consultant Jobs",
"Sap Hana Jobs",
"Aws Cloud Jobs",
"Flask Jobs",
"Integration Jobs",
"Linq Jobs",
"Mainframe Jobs",
"Mean Stack Jobs",
"Node Jobs",
"aws Jobs",
"Antivirus Jobs",
"MYSQL Jobs",
"Mulesoft Jobs",
"PHP Developer Jobs",
"PowerShell Jobs",
"Python Scripting Jobs",
"Software Services Jobs",
"Data Modelling Jobs",
"Production Incharge Jobs",
"Redis Jobs",
"Technical Documentation Jobs",
"Gl Jobs",
"Mphasis Jobs",
"Agile Scrum Jobs",
"Android Development Jobs",
"Apis Jobs",
"Hardware Support Jobs",
"Storyboards Jobs",
"j2ee Jobs",
"Network Security Jobs",
"Restful Apis Jobs",
"Sap Sd Jobs",
"Server Jobs",
"Full Stack Jobs",
"Project engineer Jobs",
"Purchase Executive Jobs",
"Sales Coordinator Jobs",
"Sap Jobs",
"User Acceptance Testing Jobs",
"Web Jobs",
"Windows Server Support Jobs",
"css Jobs",
"Advanced Excel Jobs",
"Agile Methodologies Jobs",
"Db2 Jobs",
"Js Jobs",
"Data Scientist Jobs",
"Database Management Jobs",
"Iaas Jobs",
"Iis Jobs",
"Restful Api Jobs",
"Us It Recruiter Jobs",
"Webapi Jobs",
"Aml Jobs",
"Eclipse Jobs",
"Ejb Jobs",
"Firewalls Jobs",
"Firmware Jobs",
"Rest Apis Jobs",
"Technical Process Jobs",
"Change Management Jobs",
"Ci Jobs",
"Tester Jobs",
"Vpn Jobs",
"Mongo Db Jobs",
"Support Jobs",
"Confluence Jobs",
"SQL server Jobs",
"Servicedesk Jobs",
"System Design Jobs",
"Verilog Jobs",
"Websphere Jobs",
"Bigdata Jobs",
"Ado.net Jobs",
"Change management Jobs",
"Data Mining Jobs",
"Databases Jobs",
"Ios Development Jobs",
"Desktop Jobs",
"Rabbitmq Jobs",
"Service delivery Jobs",
"Tech support Jobs",
"Wordpress Developer Jobs",
"Aix Jobs",
"Cloud Architect Jobs",
"Lambda Jobs",
"Linux Administration Jobs",
"Process Executive Jobs",
"Pyspark Jobs",
"Redshift Jobs",
"Rfp Jobs",
"Test Planning Jobs",
"Xslt Jobs",
"amadeus Jobs",
"oracle Jobs",
"Auto Cad Jobs",
"Cloud Services Jobs",
"Dreamweaver Jobs",
"MVC Framework Jobs",
"Spring MVC Jobs",
"Technical Support Officer Jobs",
"Insurance Jobs",
"Sales Jobs",
"Life Insurance Jobs",
"Bfsi Jobs",
"Bancassurance Jobs",
"Bpo Jobs",
"Banking Jobs",
"agency Jobs",
"Voice Process Jobs",
"Customer Support Jobs",
"Recruitment Jobs",
"International Bpo Jobs",
"Team Handling Jobs",
"Call Center Jobs",
"Customer Service Jobs",
"Financial Jobs",
"Bank Jobs",
"banca Jobs",
"life insurance Jobs",
"Branch Jobs",
"Team Jobs",
"Direct Jobs",
"Direct Sales Jobs",
"Customer Care Jobs",
"International Call Center Jobs",
"Back Office Jobs",
"Relationship Jobs",
"LI Jobs",
"Casa Jobs",
"Banca Jobs",
"Back Office Executive Jobs",
"Freshers Jobs",
"Inbound Jobs",
"Team Management Jobs",
"business generation Jobs",
"Fresher Jobs",
"Cross Selling Jobs",
"Data Entry Jobs",
"Capacity Building Jobs",
"Region Jobs",
"Branch Management Jobs",
"Heading Branch Jobs",
"Backend Jobs",
"Office Assistant Jobs",
"Customer Care Executive Jobs",
"Marketing Jobs",
"Data Entry Operator Jobs",
"Voice Jobs",
"Business Development Jobs",
"Graduate Fresher Jobs",
"Hr Jobs",
"Graduates Jobs",
"Undergraduates Jobs",
"Distribution Jobs",
"Outbound Jobs",
"Advisor Jobs",
"Communication Skills Jobs",
"tied Jobs",
"branch management Jobs",
"Managing Partner Jobs",
"business associates Jobs",
"Hr Executive Jobs",
"Mechanical Engineer Jobs",
"Accountant Jobs",
"High School Pass Jobs",
"Civil Engineer Jobs",
"Electrical Engineer Jobs",
"Troubleshooting Jobs",
"Human Resource Jobs",
"Telesales Jobs",
"International Voice Process Jobs",
"Hiring Jobs",
"Customer Service Executive Jobs",
"Iti Jobs",
"Voice support Jobs",
"Operations Jobs",
"Electronics Engineer Jobs",
"Staffing Jobs",
"Diploma Jobs",
"Deo Jobs",
"customer service Jobs",
"calling  Jobs",
"Digital Marketing Jobs",
"Talent Acquisition Jobs",
"b.tech Jobs",
"Cashier Jobs",
"Customer Support Executive Jobs",
"Non voice Jobs",
"Diploma Mechanical Engineer Jobs",
"Aviation Jobs",
"Degree Jobs",
"Graduate Jobs",
"Domestic BPO Jobs",
"Lead Generation Jobs",
"Finance Jobs",
"Online Marketing Jobs",
"Business Process Delivery Jobs",
"Information Technology Operations Jobs",
"US Shift Jobs",
"It Recruiter Jobs",
"Manager Jobs",
"International Voice Jobs",
"Non Voice Jobs",
"UK Shift Jobs",
"Leadership Jobs",
"Back office operations Jobs",
"Business development Jobs",
"Cash Handling Jobs",
"Business Analyst Jobs",
"Cabin Crew Jobs",
"Internet Marketing Jobs",
"Ground Staff Jobs",
"Cash Jobs",
"Executive Jobs",
"Bcom Jobs",
"Business Development Manager Jobs",
"Accounting Jobs",
"Selling Jobs",
"Consulting Jobs",
"Work From Home Jobs",
"Healthcare Jobs",
"non it recruiter Jobs",
"Non Voice Process Jobs",
"Accounts Executive Jobs",
"Business Development Executive Jobs",
"Head Cashier Jobs",
"Headhunting Jobs",
"Sourcing Jobs",
"bulk Jobs",
"niche Jobs",
"Night Shift Jobs",
"Bba Jobs",
"Manager Technology Jobs",
"Field Sales Jobs",
"Business Process Specialization Jobs",
"Cbse Jobs",
"Cpt Jobs",
"Management Jobs",
"Design Jobs",
"Undergraduate Jobs",
"Photoshop Jobs",
"Active Directory Jobs",
"Chat Jobs",
"Production Jobs",
"BA Jobs",
"Maintenance Jobs",
"Inside Sales Jobs",
"Telecalling Jobs",
"Telemarketing Jobs",
"Chat Support Jobs",
"ICSE Jobs",
"Training Jobs",
"BD Jobs",
"Medical Coding Jobs",
"Ites Jobs",
"Physiology Jobs",
"Anatomy Jobs",
"Installation Jobs",
"Java developer Jobs",
"international voice process Jobs",
"Analytical Jobs",
"Payroll Jobs",
"Security Jobs",
"Telecaller Jobs",
"Email Jobs",
"Business &amp; Technology Integration Jobs",
"CSR Jobs",
"Client Servicing Jobs",
"Hospitality Jobs",
"International Sales Jobs",
"Bsc Jobs",
"Project Management Jobs",
"Hr Manager Jobs",
"Mba Jobs",
"Counsellor Jobs",
"Engineering Jobs",
"Bdm Jobs",
"Hsc Jobs",
"Project &amp; Service Mgmt Jobs",
"Monitoring Jobs",
"Data Analysis Jobs",
"Technology Jobs",
"Quality Control Jobs",
"Relationship Management Jobs",
"Hr Generalist Jobs",
"IT Jobs",
"Illustrator Jobs",
"Computer Science Jobs",
"TSR Jobs",
"Cce Jobs",
"Operations Manager Jobs",
"Gst Jobs",
"csr Jobs",
"BPO Executive Jobs",
"Front Office Executive Jobs",
"Sales Officer Jobs",
"Education Counsellor Jobs",
"Email Support Jobs",
"Compliance Jobs",
"Counselling Jobs",
"Manufacturing Jobs",
"Air Ticketing Executive Jobs",
"Staff Nurse Jobs",
"Analytics Jobs",
"Relationship Manager Jobs",
"WFH Jobs",
"Corporate Sales Jobs",
"Petty Cash Jobs",
"B2b Sales Jobs",
"Engineer Jobs",
"Nurse Jobs",
"Salesforce Jobs",
"outbound sales Jobs",
"Typing Jobs",
"Counselor Jobs",
"Guest Relation Executive Jobs",
"Airhostess Jobs",
"Bca Jobs",
"Student Advisor Jobs",
"Home Sales Officer Jobs",
"Academic Counsellor Jobs",
"CSE Jobs",
"Taxation Jobs",
"Representative Jobs",
"Teller Jobs",
"Architecture Jobs",
"Screening Jobs",
"Tds Jobs",
"Tele Counsellor Jobs",
"Academic Counselor Jobs",
"Csa Jobs",
"Guest Relation Jobs",
"Ssc Jobs",
"Career Counselor Jobs",
"Education Counselor Jobs",
"Front Desk Jobs",
"Career Counsellor Jobs",
"Medical Coder Jobs",
"counseling Jobs",
"Call Centre Jobs",
"Mis Jobs",
"Supply Chain Jobs",
"Autocad Jobs",
"Officer Jobs",
"Developer Jobs",
"Tele Counselor Jobs",
"Chat Process Jobs",
"Nursing Jobs",
"Sales Marketing Jobs",
"Development Jobs",
"Inbound Calls Jobs",
"Mcom Jobs",
"Retail Sales Jobs",
"Hardware Jobs",
"Call Center Executive Jobs",
"Hcpcs Jobs",
"Packaging Jobs",
"Assistant Manager Jobs",
"MA Jobs",
"Outbound Sales Jobs",
"Us Mortgage Jobs",
"Administration Jobs",
"Hostess Jobs",
"Good Communication Jobs",
"ICD 10-CM Jobs",
"Back Office Support Jobs",
"CRM Jobs",
"Sales Management Jobs",
"Full Stack Developer Jobs",
"Pharmacist Jobs",
"Project management Jobs",
"Semi Voice Jobs",
"Graphic Designer Jobs",
"cse Jobs",
"Sales Executive Activities Jobs",
"Assistant Jobs",
"Technical Jobs",
"Web Marketing Jobs",
"Accounts Jobs",
"BPO Call Centre Jobs",
"Customer Relationship Jobs",
"Collections Jobs",
"Business Analysis Jobs",
"Generalist Jobs",
"Relationship manager Jobs",
"Associate Jobs",
"Channel Sales Jobs",
"Analytical Skills Jobs",
"first source Jobs",
"Outbound Calling Jobs",
"Production Support Jobs",
"Airlines Jobs",
"Counter Sales Jobs",
"Customer Handling Jobs",
"Vault Custodian Jobs",
"Uk Jobs",
"Accounts Payable Jobs",
"Customercare executive Jobs",
"Gnm Jobs",
"Sr. Cabin Crew Jobs",
"business development Jobs",
"Architect Jobs",
"Front Office Jobs",
"Life Science Jobs",
"Design Engineer Jobs",
"Fmcg Jobs",
"Accounts Manager Jobs",
"B2b Jobs",
"Marketing Executive Jobs",
"Outbound Process Jobs",
"Software Jobs",
"Team Lead Jobs",
"Finance Executive Jobs",
"Pharma Jobs",
"Sales And Marketing Jobs",
"Negotiation Jobs",
"Bde Jobs",
"Hindi Jobs",
"Inventory Jobs",
"Site Engineer Jobs",
"Recruiter Jobs",
"inside sales Jobs",
"3D Animation Jobs",
"Compensation And Benefits Jobs",
"Marketing Manager Jobs",
"Cold Calling Jobs",
"Ir Jobs",
"Product Development Jobs",
"Bhm Jobs",
"Electrical Maintenance Jobs",
"Domestic Bpo Jobs",
"Logistics Jobs",
"Account assistant Jobs",
"infosys Jobs",
"Interpersonal Skills Jobs",
"Admin Executive Jobs",
"Audit Jobs",
"Banking Operations Jobs",
"Data Entry Executive Jobs",
"Us Process Jobs",
"CI/CD Jobs",
"Customer Jobs",
"Hr Analyst Jobs",
".Net Developer Jobs",
"12th pass Jobs",
"English Jobs",
"Hr Audit Jobs",
"Site Supervisor Jobs",
"Warehouse Jobs",
"Implementation Jobs",
"Key Account Manager Jobs",
"Sales Targets Jobs",
"Accounts Officer Jobs",
"Analytics and Insights Jobs",
"General Ledger Jobs",
"Human Resources Jobs",
"Production Manager Jobs",
"Management Consulting Jobs",
"maintenance Jobs",
"Customer Service Representative Jobs",
"Purchase Jobs",
"International Process Jobs",
"Agency Manager Jobs",
"Banking Sales Jobs",
"Problem Solver Jobs",
"UI Developer Jobs",
"communication Jobs",
"Bbm Jobs",
"Inbound Process Jobs",
"Service Desk Jobs",
"Helper Jobs",
"Infrastructure Jobs",
"Helpdesk Jobs",
"Procurement Jobs",
"Front Desk Executive Jobs",
"Mechanical Jobs",
"Product Sales Jobs",
"Stakeholder Management Jobs",
"domestic bpo Jobs",
"Hotel Management Jobs",
"Indesign Jobs",
"Phone Banking Officer Jobs",
"Application Developer Jobs",
"Trainee Jobs",
"isc Jobs",
"international call centre Jobs",
"Deployment Jobs",
"Back Office Operations Jobs",
"International Jobs",
"International Marketing Jobs",
"android developer Jobs",
"Auditing Jobs",
"Typist Jobs",
"Advisory Jobs",
"Customer service Jobs",
"Domestic Jobs",
"Pharmacy Jobs",
"Sales Representative Jobs",
"Account Manager Jobs",
"Chef Jobs",
"Project Planning Jobs",
"3D Artist Jobs",
"Automobile Jobs",
"Part Time Job Jobs",
".NET Framework Jobs",
"Electrical Jobs",
"Medical Billing Jobs",
"Training Manager Jobs",
"Delivery Boy Jobs",
"Fresher BPO Jobs",
"ticket reservations Jobs",
"Content Writer Jobs",
"Online Job Jobs",
"Travel Jobs",
"Lead Jobs",
"Area Sales Manager Jobs",
"Field Work Jobs",
"Mis Executive Jobs",
"day shift Jobs",
"Medical Jobs",
"Mortgage Jobs",
"Problem Solving Jobs",
"Social Media Jobs",
"Inside sales Jobs",
"Online Sales Jobs",
"Reconciliation Jobs",
"V-Ray Jobs",
"Client Acquisition Jobs",
"accounting Jobs",
"Computer Jobs",
"DEO Jobs",
"It Staffing Jobs",
"Us Healthcare Jobs",
"Pathology Jobs",
"Non Voice Bpo Jobs",
"Corporate Selling Jobs",
"Direct Marketing Jobs",
"Hotel Jobs",
"R Jobs",
"Retail Pharmacist Jobs",
"Customer Support Associate Jobs",
"Data Processing Jobs",
"Hospital Pharmacist Jobs",
"Motion Graphics Jobs",
"Sharepoint Jobs",
"Underwriting Jobs",
"Mechanical Engineering Jobs",
"People Management Jobs",
"Ticketing Jobs",
"project management Jobs",
"Client Management Jobs",
"Desktop Support Engineer Jobs",
"Inventory Management Jobs",
"Key Account Jobs",
"Corel Draw Jobs",
"Documentation Jobs",
"Process Jobs",
"Advertising Jobs",
"Icd Jobs",
"Msc Jobs",
"Supervisor Jobs",
"Biotech job Jobs",
"Construction Jobs",
"Medical Coder job Jobs",
"Medical coding job Jobs",
"Nursing job Jobs",
"Pharmacy job Jobs",
"dentist job Jobs",
"microbiology job Jobs",
"physiotherapist jobs Jobs",
"staff Nurse Job Jobs",
"Field Sales Executive Jobs",
"Front office Jobs",
"Hr Recruiter Jobs",
"Paramedica Jobs",
"Sales Process Jobs",
"ios developer Jobs",
"Accounts Assistant Jobs",
"BE Jobs",
"CAD Jobs",
"Construction Engineer Jobs",
"Content Writing Jobs",
"Microbiology Jobs",
"Assistant Sales Manager Jobs",
"Budgeting Jobs",
"BPO Fresher Jobs",
"Data Analyst Jobs",
"Financial Services Jobs",
"Data Science Jobs",
"Manufacturing Engineer Jobs"]

import sys
import pandas as pd
link="https://www.monsterindia.com/search/"
link1 ="https://www.monsterindia.com/search/java-jobs"
driver = webdriver.Chrome(executable_path='/home/maxbot/.wdm/drivers/chromedriver/linux64/83.0.4103.39/chromedriver')
driver_links = webdriver.Chrome(executable_path='/home/maxbot/.wdm/drivers/chromedriver/linux64/83.0.4103.39/chromedriver')


def extractJobLinks(html):
    job_links = []
    try:
        soup=BeautifulSoup(html, 'lxml')
        job_lists=soup.find("div",{"id":"srp-jobList"}).find_all("div",{"class":"card-panel apply-panel job-apply-card"})
        cnt=0
        for jobs_div in job_lists:
            job_title=jobs_div.find_all("div",{"class":"job-tittle"})
            if(len(job_title)):
                cnt=cnt+1
                link=job_title[0].find_all("a", href=True)
                job_links.append(link[0]['href'])
            if(cnt==25):
                break
    except:
        e = sys.exc_info()[0]
        print(e,"   extractJobLinks")
        error=1
    return job_links

def getWebpage(link):
    driver.get(link)
    source=driver.page_source
    return source

def getjdText(soup):
    try:
        jd_div=soup.find("div",{"id":"description"})
        jd_text_div=jd_div.find_all("div",{"class":"jd-text"})

        return jd_text_div[0].text
    except:
        e = sys.exc_info()[0]
        print(e,"   getjdText")
        error = 1
        return " "

def getjdSkills(soup):
    try:
        jd_skills_list = []
        jd_skillset_div=soup.find("div",{"id":"jobDets"})
        job_detail_list=jd_skillset_div.find_all("div",{"class":"job-detail-list"})
        skills_div=job_detail_list[3].find_all("div",{"class":"dt-content"})[0]
        skills_span_list=skills_div.find_all("span",{"class":"round-card mb5 grey-link"})
        for skill in skills_span_list:
            text=skill.find_all("a")
            jd_skills_list.append(text[0].text.strip())
    except:
        e = sys.exc_info()[0]
        print(e, "   getjdSkills")

    return(jd_skills_list)

def insertIntoCSV(data):
    field_names = ['category', 'text', 'skills']
    with open('jobs_classify.csv','a+', newline='') as csvfile:
        dict_writer = csv.DictWriter(csvfile, fieldnames=field_names)
        for d in data:
            dict_writer.writerow(d)

def parseLinks(links,category):
    data=[]
    for link in links:
        driver_links.get(link)
        source=driver_links.page_source
        soup=BeautifulSoup(source, 'lxml')
        skills=getjdSkills(soup)
        jd_text=getjdText(soup)
        skills_text="none"
        if(len(skills)):
            skills_text=",".join(skills)
        temp_data={
            "category":category,
            "text":jd_text,
            "skills":skills_text
        }
        if(temp_data["text"]==" " and  len(temp_data["skills"])==0):
            return -1
        data.append(temp_data)
        time.sleep(1)

    insertIntoCSV(data)


def convertCategory(category):
    text=category.lower()
    newText="-".join(text.split())
    return newText

def insertCategory(category):
    fields=["category"]
    data=[{"category":category}]
    with open('category.csv', 'a+',newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fields)
        writer.writerows(data)


category_data=pd.read_csv("category.csv")

category_parsed=category_data["category"].tolist()

jobs_lists=jobs_list.reverse()
for category in jobs_list:
    if category not in category_parsed:
        link2=link+convertCategory(category)
        print("Parsing for",category)
        print(link2)
        html=getWebpage(link2)
        jobs_links=extractJobLinks(html)
        error=parseLinks(jobs_links,category)
        if(error==-1):
            print("ERROR... Breaking..")
        insertCategory(category)
        print("------------ Done parsing -------- ", category)
        time.sleep(5)



# parseLinks(["https://www.monsterindia.com/job/hiring-java-technical-lead-kumaran-systems-chennai-kumaran-systems-private-limited-chennai-2078435?searchId=c1050005-ed65-4462-8f97-9514e7a0184d"],"java")
